services:
  - type: web
    name: tts-api
    env: node
    buildCommand: npm install
    startCommand: node server/app.js
    plan: free
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/google_credentials_json
